# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CA-AutoSys
version:      1.05
version_from: lib/CA/AutoSys.pm
installdirs:  site
requires:
    DBI:                           

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
